### ISSUE TITLE
Is it possible to embed an android view in a Godot screen

### ISSUE THREAD

**Issue by kyadalu1** [m4gr3d/Godot-Android-Plugins#10]
I have gone through your Gltf app where you are embedding Godot view in an android app. Is the reverse possible? I know this might sound a bit odd. But if you conside my background i don't have my knowledge in Godot but i have decent knowledge in native android development. Suppose for example there is no third part lib for integrating android camera in godot, do you have any idea or a sample repo or docs on how should i go about embedding a native android view in a godot game? I have gone through [this](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html#building-a-v2-android-plugin) but this feels more like intgrating business logic stuff of android in Godot and not embedding UI. Thanks.

**Comment by m4gr3d** [comment]
@kyadalu1 It was possible in Godot 3 using the [GAST plugin](https://github.com/m4gr3d/GAST), but that functionality has yet to be forward ported in Godot 4.

There's a [draft PR](https://github.com/godotengine/godot/pull/83519) to start discussing how it can be brought back to Godot 4 with the goal of trying to have the feature available in the Godot 4.3 release.

**Comment by m4gr3d** [comment]
Once the functionality is brought back, the integration mechanism will also be via an [Android plugin](https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html#building-a-v2-android-plugin), where the plugin gets access to a `Surface` from Godot where it can render Android views, and the `Surface` output is rendered within Godot's scenegraph.

**Comment by kyadalu1** [comment]
Thank you
