### ISSUE TITLE
What is the MainActivity equivalent in Godot? Is it GodotActivity?

### ISSUE THREAD

**Issue by BraveEvidence** [m4gr3d/Godot-Android-Plugins#17]
I am trying to create an android plugin for Godot. Basically I want to create a dynamic shortcut. So the code for making dynamic shortcut requires a proper activity. Below is my code

```
 @UsedByGodot
    private fun addDynamicShortCut() {
        runOnUiThread {
            val shortcut = activity?.applicationContext?.let {
                ShortcutInfoCompat.Builder(it, "dynamic")
                    .setShortLabel("Like Coding with Nobody")
                    .setLongLabel("Clicking this will like coding with nobody")
                    .setIcon(
                        IconCompat.createWithResource(
                            activity?.applicationContext!!,
                            R.drawable.baseline_arrow_outward_24
                        )
                    )
                    .setIntent(
                        Intent(activity?.applicationContext, GodotActivity::class.java).apply {
                            action = Intent.ACTION_VIEW
                            putExtra("shortcut_id", "dynamic")
                        }
                    ).build()
            }
            shortcut?.let {
                activity?.applicationContext?.let { it1 ->
                    ShortcutManagerCompat.pushDynamicShortcut(
                        it1,
                        it
                    )
                }
            }
        }
    }
```

As you can see I am using `GodotActivity::class.java` in the above code. I can see my dynamic shortcut being added to my game but when I try to click on it I get `App isn't installed` message

Check below video
https://github.com/m4gr3d/Godot-Android-Samples/assets/24708929/b686daaa-4dee-4687-84a4-42f2bdfe6492

**Comment by BraveEvidence** [comment]
Going through the android folder of Godot after installing android build template I see GodotApp as the main activity but I cannot access it while creating a plugin. 
<img width="1318" alt="Screenshot 2024-02-01 at 8 35 29 PM" src="https://github.com/m4gr3d/Godot-Android-Samples/assets/24708929/fe728d32-4cfd-4e37-94a8-a49a23f5771c">

**Comment by m4gr3d** [comment]
Since you're writing a plugin, you don't want to hardcode the main activity as developers can modify what that main activity is. 

Instead, you can use an [implicit intent](https://developer.android.com/guide/components/intents-filters#ExampleSend) to automatically target the main activity using the `Intent.ACTION_MAIN` action.
Furthermore, you can restrict your intent to the app that's running your plugin by specifying the app package name using `activity?.packageName`

**Comment by BraveEvidence** [comment]
Thank you
