### ISSUE TITLE
Build Failure in gltf_viewer: Resource name must contain only lowercase files

### ISSUE THREAD

**Issue by luc4smoreira** [m4gr3d/Godot-Android-Plugins#3]
**Environment**

IDE: Android Studio Giraffe | 2022.3.1 
Computer:  Mac mini Apple M1

**Description**

I encountered a build failure when trying to run the gltf_viewer app in the Godot-Android-Samples project. The issue seems to be related to a resource naming convention.

**Steps do Reproduce:**

1. Clone the repository
2. Run the command:
`./gradlew :apps:gltf_viewer:installDebug`
3. Observe the build failure:

> Godot-Android-Samples/apps/gltf_viewer/src/main/res/drawable-nodpi/iceCreamCup.png: Resource and asset merger: 'C' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
> 
> FAILURE: Build failed with an exception.
 
 **Fix**

To fix this issue, I have renamed the files to lowercase in the folder:

`Godot-Android-Samples/apps/gltf_viewer/src/main/res/drawable-nodpi`

This aligns with the Android naming conventions that require resource names to be all in lowercase. 

Unfortunately, I am unable to create a pull request for this change as GitHub is not recognizing the difference in file names due to case sensitivity issues.

**Comment by m4gr3d** [comment]
Thanks for re-opening the issue!

I thought I had renamed all the files to lowercase but I may have missed some. I'll do another pass and see if force-pushing to the repo will update them.
