### ISSUE TITLE
Update Godot Android Library to use the stable version: 4.2.0.stable

### ISSUE THREAD

**Issue by luc4smoreira** [m4gr3d/Godot-Android-Plugins#6]
I propose a minor yet impactful update to the **config.gradle** to use the latest stable version . The aim is to remove the test code and 'TODO' comments from the samples, enhancing the codebase's clarity and maintainability. Here is the suggested update:

```
ext {
    versions = [
            gradlePluginVersion: '7.4.0',
            compileSdk         : 33,
            minSdk             : 21,
            targetSdk          : 33,
            javaVersion        : JavaVersion.VERSION_11,
            kotlinVersion      : '1.8.22',
    ]

    libraries = [
            godotAndroidLib: "org.godotengine:godot:4.2.0.stable",
    ]
}
```

This update aligns the project with the stable version of Godot (4.2.0.stable), ensuring better stability and compatibility.

**Comment by m4gr3d** [comment]
Fixed by https://github.com/m4gr3d/Godot-Android-Samples/pull/7
