### ISSUE TITLE
Unable to send data from native android to Godot via signals

### ISSUE THREAD

**Issue by kyadalu1** [m4gr3d/Godot-Android-Plugins#9]
I am trying to integrate signals via android plugin. Below is my android code

```
class GodotAndroidPlugin(godot: Godot) : GodotPlugin(godot) {

    override fun getPluginName() = "MyPlugin"


    override fun getPluginSignals(): MutableSet<SignalInfo> {
        val signals: MutableSet<SignalInfo> = mutableSetOf();
        signals.add(SignalInfo("testSignal", String::class.java))
        return signals
    }

    @UsedByGodot
    private fun helloWorldSignal(name: String) {
        runOnUiThread {
            Toast.makeText(activity, "Hello $name", Toast.LENGTH_LONG).show()
            emitSignal("testSignal", "Hello $name")
        }
    }

}
```

When i call the `helloWorldSignal` method from Godot side i am able to see the `Toast` but i am not able to get the data which i am sending using the `emitSignal` method

My Godot code

```
var _plugin_name = "MyPlugin"
var _android_plugin

func _ready():
	if Engine.has_singleton(_plugin_name):
		_android_plugin = Engine.get_singleton(_plugin_name)
		_android_plugin.connect("testSignal",self,"on_testSignal")
	else:
		printerr("Couldn't find plugin " + _plugin_name)

func _on_button_2_pressed() -> void:
	if _android_plugin:
		_android_plugin.helloWorldSignal("Shivaji")

func on_testSignal(data):
	label.text = data
	print(data)
```

`on_testSignal` is never called. 

I tried looking into the signal repo which you have created but you're not sending any data from native android to godot side. Sorry i am pretty new to Godot

**Comment by m4gr3d** [comment]
@kyadalu1 The syntax you're using to register the signal is incorrect; you can either use

```
_android_plugin.connect("testSignal", Callable(self,"on_testSignal"))
```

or 
```
_android_plugin.connect("testSignal", on_testSignal)
```


> I tried looking into the signal repo which you have created but you're not sending any data from native android to godot side.

The [gltf viewer sample](https://github.com/m4gr3d/Godot-Android-Samples/tree/master/apps/gltf_viewer) sends a signal with a `String` data, you can use it for reference.
- [signal emission](https://github.com/m4gr3d/Godot-Android-Samples/blob/ec41ea1b230eb00c8f37ee37c197ec8b450cba02/apps/gltf_viewer/src/main/java/fhuyakou/godot/app/android/gltfviewer/AppPlugin.kt#L26)
- [signal connection](https://github.com/m4gr3d/Godot-Android-Samples/blob/ec41ea1b230eb00c8f37ee37c197ec8b450cba02/apps/gltf_viewer/src/main/assets/main.gd#L15)

**Comment by kyadalu1** [comment]
Thank you
